_target_: lidar_prod.tasks.building_completion.BuildingCompletor

data_format: ${data_format}

min_building_proba: 0.5

cluster:
  min_points: 10 # including isolated points (in BuildingValidator) and confirmed candidates points.
  tolerance: 0.3 # meters, small to capture building superstructures only
  is3d: false # group in 2d for better detection
