_target_: lidar_prod.tasks.building_identification.BuildingIdentifier

candidate_buildings_codes: ${data_format.codes.candidates.building}

data_format: ${data_format}

min_building_proba: ${building_validation.application.rules.min_confidence_confirmation}
min_building_proba_multiplier_if_bd_uni_overlay: 0.5

cluster:
  min_points: 200
  tolerance: 1  # meters
  is3d: false  # group in 2d for better detection

