# @package _global_
print_config: True
ignore_warnings: True

# specify here default training configuration
defaults:
  - hydra: default.yaml
  - paths: default.yaml
  - data_format: default.yaml
  - building_validation: default.yaml
  - _self_