# @package _global_
print_config: False
ignore_warnings: True
# specify here default training configuration
defaults:
  - hydra: default.yaml
  - paths: default.yaml
  - data_format: default.yaml
  - building_validation: default.yaml
  - building_identification: default.yaml
  - building_completion: default.yaml
  - basic_identification: default.yaml
  - bd_uni_connection_params: credentials.yaml
  - _self_  # needed by pdal for legacy reasons